version: '3.8'

services:
  db:
    image: ankane/pgvector:latest
    environment:
      POSTGRES_DB: intellibuy_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-HEALTCHECK", "pg_isready", "-U", "seu_usuario"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

volumes:
  db_data: